services:
  db:
    image: postgres:18
    container_name: marvelmarts-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Rxes76$#@L
      POSTGRES_DB: marvelmarts_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  web:
    build: .
    container_name: marvelmarts-web
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://postgres:Rxes76%24%23%40L@db:5432/marvelmarts_db
     
      volumes:
       .:/app
    working_dir: /app
    command: ["sh", "./start.sh"]

volumes:
  pgdata: